package de.dewarim.goblin.shop

import de.dewarim.goblin.Dice

/**
 * Owner of a shop. At the moment, shop owners are not strictly necessary (the fields
 * could be rolled into the shop class), but later on we might want race specific shop owners
 * like in Moria and Angband.
 */
class ShopOwner {

    static hasMany = [shops:Shop]

	static constraints = {
		name blank:false
		description blank:false
	}

	/**
	 * This dice is the factor by how many % the price of items will be adjusted.
	 */
	Dice priceModifierDice

    /**
     * The value generated by the priceModifierDice is stored in priceModifier. Later on,
     * it should be re-rolled every day or so to create price changes.
     */
    Integer priceModifier = 1

	String name
	String description

   void calculatePriceModifier(){
     priceModifier = priceModifierDice.roll()
   }



    /**
    *
    * Calculate how much a player character has to pay
    * @param item the itemType
    * @return price in gold pieces
   */
  Integer calculatePrice(itemType){
    return itemType.baseValue + (itemType.baseValue * priceModifier/100).intValue()
  }



    /**
     * Calculate how much the shop owner will pay for a given item.
     * He will generally pay half of what it's worth.
     * @param item the player's item
     * @return the price the item will fetch from this shop owner.
     */
    Integer calculateSellPrice(item){
        return (item.type.baseValue / 2).intValue() +1
    }

    boolean equals(o) {
        if (is(o)) return true
        if (!(o instanceof ShopOwner)) return false

        ShopOwner shopOwner = o

        if (description != shopOwner.description) return false
        if (name != shopOwner.name) return false
        if (priceModifier != shopOwner.priceModifier) return false
        if (priceModifierDice != shopOwner.priceModifierDice) return false

        return true
    }

    int hashCode() {
        int result
        result = (priceModifierDice != null ? priceModifierDice.hashCode() : 0)
        result = 31 * result + (priceModifier != null ? priceModifier.hashCode() : 0)
        result = 31 * result + (name != null ? name.hashCode() : 0)
        result = 31 * result + (description != null ? description.hashCode() : 0)
        return result
    }
}
